module.exports = {
  missingParams: {
    requestStatus: 200,
    status: 406,
    message: 'missing params',
    data: {},
    notifications: [],
  },
  wrongUsernamePassword: {
    requestStatus: 200,
    status: 404,
    message: 'wrong username or password (not found the account)',
    data: {},
    notifications: [],
  },
  loginSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'login successfully',
    data: {},
    notifications: [],
  },
  logoutSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'logout successfully',
    data: {},
    notifications: [],
  },
  usernameExisted: {
    requestStatus: 200,
    status: 406,
    message: 'username existed',
    data: {},
    notifications: [],
  },
  emailExisted: {
    requestStatus: 200,
    status: 406,
    message: 'email existed',
    data: {},
    notifications: [],
  },
  objectExisted: {
    requestStatus: 200,
    status: 406,
    message: 'object existed',
    data: {},
    notifications: [],
  },
  createAccountSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'create new account successfully',
    data: {},
    notifications: [],
  },
  notFoundEmail: {
    requestStatus: 200,
    status: 404,
    message: 'not found the email',
    data: {},
    notifications: [],
  },
  notFoundAccount: {
    requestStatus: 200,
    status: 404,
    message: 'not found the account',
    data: {},
    notifications: [],
  },
  spadminRejectUpdate: {
    requestStatus: 200,
    status: 406,
    message: 'reject updating spadmin\'s infomations',
    data: {},
    notifications: [],
  },
  updateSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'update successfully',
    data: {},
    notifications: [],
  },
  getListSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'get list successfully',
    data: {},
    notifications: [],
  },
  getOneSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'get data successfully',
    data: {},
    notifications: [],
  },
  rejectDelete: {
    requestStatus: 200,
    status: 406,
    message: 'reject delete',
    data: {},
    notifications: [],
  },
  rejectUpdate: {
    requestStatus: 200,
    status: 406,
    message: 'reject update',
    data: {},
    notifications: [],
  },
  deleteSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'delete successfully',
    data: {},
    notifications: [],
  },
  noPermission: {
    requestStatus: 200,
    status: 403,
    message: 'have no permission to access this URL',
    data: {},
    notifications: [],
  },
  noData: {
    requestStatus: 200,
    status: 406,
    message: 'have no any data to handle',
    data: {},
    notifications: [],
  },
  dataExisted: {
    requestStatus: 200,
    status: 406,
    message: 'this data is Existed',
    data: {},
    notifications: [],
  },
  error: {
    requestStatus: 200,
    status: 406,
    message: 'some errors appear',
    data: {},
    notifications: [],
  },
  badRequest: {
    requestStatus: 200,
    status: 400,
    message: 'some errors appear',
    data: {},
    notifications: [],
  },
  notFound: {
    requestStatus: 200,
    status: 404,
    message: 'not found any data',
    data: {},
    notifications: [],
  },
  insertSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'create data successfully',
    data: {},
    notifications: [],
  },
  noFileUpload: {
    requestStatus: 200,
    status: 400,
    message: 'No files were uploaded',
    data: {},
    notifications: [],
  },
  fileUploadSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'upload successfully',
    data: {},
    notifications: [],
  },
  authen: {
    requestStatus: 200,
    status: 401,
    message: 'Unauthorized',
    data: {},
    notifications: [],
  },
  restartSuccess: {
    requestStatus: 200,
    status: 200,
    message: 'restart successfully',
    data: {},
    notifications: [],
  },
  isUsing: {
    requestStatus: 200,
    status: 406,
    message: 'object is using',
    data: {},
    notifications: [],
  },
};